baseURL = "/"
themesDir = "themes"
theme = "hugo-serif"
languageCode = "en-us"
title = "OSGeo Brasil"

[module]
  [module.hugoVersion]
    extended = true
    min = "0.55.0"

[params]
  # In most cases you will only want to set the google_analytics_id OR the google_tag_manager_id. If you have Google Analytics included in your GTM tags don't put your GA ID here. Otherwise your data might be useless.
  google_analytics_id = ""
  google_tag_manager_id = ""
  favicon = "/images/logo.png"

  [params.homepage]
    show_contact_box = true     # show / hide the contaxt box on the homepage
    show_services_button = true # show / hide the "view all services" button

  [params.logo]
    mobile = "images/logo.png"
    mobile_height = "36px"
    desktop = "images/osgeobr.png"
    desktop_height = "36px"
    alt = "OSGeo Brasil"

  [params.fonts]
    # sets the google font link in layouts/partials/google-fonts.html
    google_fonts = 'https://fonts.googleapis.com/css2?family=Roboto+Serif:ital,opsz,wght@0,8..144,100..900;1,8..144,100..900&family=Roboto:ital,wght@0,100;0,300;0,400;0,500;0,700;0,900;1,100;1,300;1,400;1,500;1,700;1,900&display=swap" rel="stylesheet"'
    heading = "Roboto+Serif"
    base = "Roboto"

  [params.colors]
    primary = "#339966"
    black = "#333333"
    white = "#ffffff"
    white_offset = "#f6f7ff"
    grey = "#666666"

  [params.seo]
    meta_twitter_site = ""
    meta_twitter_creator = ""
    meta_og_image = ""

  [params.services]
    summary_truncate = 120 # How many characters to include in the summary of the services before truncating

  [params.team]
    summary_large_truncate = 120 # How many characters to include in the summary of the team bios (large layout) before truncating

  [params.footer]
    copyright_text = '&copy 2024 | OSGeo Brasil'

[menu]
  # Main Menu
  [[menu.main]]
    name = "Publicações"
    url = "/services/"
    weight = 3

  [[menu.main]]
    name = "Equipe"
    url = "/team/"
    weight = 2

  [[menu.main]]
    name = "Sobre"
    url = "/about/"
    weight = 1

  [[menu.main]]
    name = "Contato"
    url = "/contact/"
    weight = 4

  [[menu.main]]
    name = "Wiki"
    url = "https://wiki.osgeo.org/wiki/Brasil"
    weight = 5

  # Footer Menu
  [[menu.footer]]
    name = "Início"
    url = "/"
    weight = 1

  [[menu.footer]]
    name = "Contato"
    url = "/contact/"
    weight = 2
